# Generated by Django 4.2.6 on 2023-10-17 02:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pages", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="title",
            field=models.CharField(default="Title", max_length=100),
        ),
    ]
