# Generated by Django 4.2.6 on 2023-11-01 03:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pages", "0002_post_title"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="author",
            field=models.CharField(default="Author", max_length=200),
        ),
        migrations.AlterField(
            model_name="post",
            name="title",
            field=models.CharField(default="Title", max_length=200),
        ),
    ]
